### ISSUE TITLE
timed browser tabs self destruct

### ISSUE THREAD

**Issue by techieshark** [techieshark/ideas#30]
A browser extension that automatically closes all your browser tabs every day at midnight. This is for people that don't have the self control to do it themselves.

- Stealing this idea from @mollymcleod

https://twitter.com/mollyampersand/status/585901407552704514

**Comment by mollymcleod** [comment]
I just found this which seems to do the trick... https://chrome.google.com/webstore/detail/tab-wrangler/egnjhciaieeiiohknchakcodbpgjnchh?hl=en

**Comment by techieshark** [comment]
@mollymcleod alright, issue closed! 

it looks like it closes tabs after a set amount of time rather than at midnight. I assume you would just tell it to close after 6 hours of inactivity, and... as long as your computer is on while you sleep it'll clean them up, or maybe it closes the tabs as soon as your computer wakes up in the morning.
